const ACTIONS = {
    MOVIE_LOADER: 'MOVIE_LOADER',
    GET_MOVIE_SUCCESS: 'GET_MOVIE_SUCCESS',
    GET_MOVIE_ERROR: 'GET_MOVIE_ERROR',
    SEARCH_MOVIE_SUCCESS: 'SEARCH_MOVIE_SUCCESS',
    SEARCH_MOVIE_ERROR: 'SEARCH_MOVIE_ERROR',
    RESET_SEARCH_DATA: 'RESET_SEARCH_DATA',
    ADD_MOVIE_SUCCESS: 'ADD_MOVIE_SUCCESS',
    ADD_MOVIE_ERROR: 'ADD_MOVIE_ERROR',
    EDIT_MOVIE_SUCCESS: 'EDIT_MOVIE_SUCCESS',
    EDIT_MOVIE_ERROR: 'EDIT_MOVIE_ERROR',
    DELETE_MOVIE_SUCCESS: 'DELETE_MOVIE_SUCCESS',
    DELETE_MOVIE_ERROR: 'DELETE_MOVIE_ERROR',
    PUT_MESSAGE_ADD_MOVIE_SUCCESS: 'NOTE_SUCCESS_ADDED_ADD_MOVIE_SUCCESS',
    UPDATE_PARAMS: 'UPDATE_PARAMS',
    RESET_PARAMS: 'RESET_PARAMS',
}

export default ACTIONS;
