const ACTIONS = {
    GET_MOVIE: 'GET_MOVIE',
    GET_MOVIE_SUCCESS: 'GET_MOVIE_SUCCESS',
    GET_MOVIE_ERROR: 'GET_MOVIE_ERROR',
    GET_MOVIE_LOADING: 'GET_MOVIE_LOADING',
    ADD_MOVIE: 'ADD_MOVIE',
    EDIT_MOVIE: 'EDIT_MOVIE',
    DELETE_MOVIE: 'DELETE_MOVIE',
    SHOW_LOADER: 'SHOW_LOADER',
    HIDE_LOADER: 'HIDE_LOADER',
}

export default ACTIONS;

