const ACTIONS = {
    MOVIE_LOADER: 'MOVIE_LOADER',
    GET_MOVIE_SUCCESS: 'GET_MOVIE_SUCCESS',
    GET_MOVIE_ERROR: 'GET_MOVIE_ERROR',
    GET_MOVIE_BY_ID_SUCCESS: 'GET_MOVIE_BY_ID_SUCCESS',
    GET_MOVIE_BY_ID_ERROR: 'GET_MOVIE_BY_ID_ERROR',
    ADD_MOVIE_SUCCESS: 'ADD_MOVIE_SUCCESS',
    ADD_MOVIE_ERROR: 'ADD_MOVIE_ERROR',
    EDIT_MOVIE_SUCCESS: 'EDIT_MOVIE_SUCCESS',
    EDIT_MOVIE_ERROR: 'EDIT_MOVIE_ERROR',
    DELETE_MOVIE_SUCCESS: 'DELETE_MOVIE_SUCCESS',
    DELETE_MOVIE_ERROR: 'DELETE_MOVIE_ERROR',
    PUT_MESSAGE_ADD_MOVIE_SUCCESS: 'NOTE_SUCCESS_ADDED_ADD_MOVIE_SUCCESS',
}

export default ACTIONS;
