const ACTIONS = {
    MOVIE_LOADER: 'MOVIE_LOADER',
    GET_MOVIE_SUCCESS: 'GET_MOVIE_SUCCESS',
    GET_MOVIE_ERROR: 'GET_MOVIE_ERROR',
    ADD_MOVIE_SUCCESS: 'ADD_MOVIE_SUCCESS',
    ADD_MOVIE_ERROR: 'ADD_MOVIE_ERROR',
    EDIT_MOVIE_SUCCESS: 'EDIT_MOVIE_SUCCESS',
    EDIT_MOVIE_ERROR: 'EDIT_MOVIE_ERROR',
    DELETE_MOVIE_SUCCESS: 'DELETE_MOVIE_SUCCESS',
    DELETE_MOVIE_ERROR: 'DELETE_MOVIE_ERROR',
}

export default ACTIONS;

